config/routes.rb
App::Application.routes.draw do
  resources :orders

  get "cart/index"
  get "site/about"
  get "site/contact"
  get "site/login"
  get "site/register"
  get "site/cart"
  resources :items
  
  get '/about' => 'site#about'
  get '/contact' => 'site#contact' 
  get '/login' => 'site#login'
  get '/register' => 'site#register'
  get '/cart' => 'site#cart'
  get '/cart' => 'cart#index'
  get 'cart/:id' => 'cart#add'
  
  
  get '/Admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  
  resources :orders do
  	resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category)
    end
    
	# GET /orders/1/items
	def index
		# For URL like /orders/1/items
		# Get the order with id=1
		@order = Order.find(params[:order_id])
		
		# Access all items for that order
		@items = @order.items
	end
	
		# GET /orders/1/items/2
	def show
		@order = Order.find(params[:order_id])
	
		# For URL like /orders/1/items/2
		# Find an item in orders 1 that has id=2
		@item = @order.items.find(params[:id])
	end
	
		# GET /orders/1/items/new
	def new
		@order = Order.find(params[:order_id])
		
		
		# Associate an item object with order 1
		@item = @order.items.build
	end
	
		# POST /orders/1/items
	def create
		@order = Order.find(params[:order_id])
		# For URL like /orders/1/items
		# Populate an item associate with order 1 with form data
		# Order will be associated with the item
		@item = @order.items.build(params[:item])
		if @item.save
			# Save the item successfully
			redirect_to order_item_url(@order, @item)
		else
			render :action => "new"
		end
	end
	
		# GET /orders/1/items/2/edit
	def edit
	@order = Order.find(params[:order_id])
		# For URL like /orders/1/items/2/edit
		# Get item id=2 for order 1
    	@item = @order.items.find(params[:id])
	end
	
		# PUT /orders/1/items/2
	def update
		@order = Order.find(params[:order_id])
		@item = Item.find(params[:id])
		if @item.update_attributes(params[:item])
    		# Save the item successfully
		redirect_to order_item_url(@order, @item)
		else
			render :action => "edit"
		end
	end

		# DELETE /orders/1/items/2
	def destroy
		@order = Order.find(params[:order_id])
		@item = Item.find(params[:id])
		@item.destroy
		
		respond_to do |format|
			format.html { redirect_to order_items_path(@order) }
			format.xml { head :ok }
		end
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@order, @item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', order_item_path (@order, @item) %> |
<%= link_to 'Back', order_items_path(@orser) %>

app/views/items/index.html.erb
<h1>Items in <%= @order.order_name %></h1>
<table>
<tr>
<th>Item name</th>
</tr>
<%
for
item in @items %>
<tr>
<td><%= item.item_name %></td>
<td><%= link_to'Show', order_item_path(@order, item) %></td>
<td><%= link_to 'Edit', edit_order_item_path(@order, item) %></td>
<td><%= link_to 'Destroy', order_item_path(@order, item), :confirm =>
'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
</
table>
<br />
<%= link_to 'New item', new_order_item_path(@order) %>
<%= link_to 'Back to Order', @order %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path(@order) %>

app/views/items/show.html.erb
<H1>Item in <%= order.order_name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order, @item) %> |
<%= link_to 'Back', order_items_path(@order) %>